### ISSUE TITLE
Events and Alerts should be shown only for the relevant PowerPlant

### ISSUE THREAD

**Issue by joesan** [sebastianvoss/plant-simulator-ui#1]
Currently, the evens and alerts widget for PowerPlant 1 can also be seen for the PowerPlant 2. Can we just show the events and alerts for the corresponding PowerPlant?

**Comment by sebastianvoss** [comment]
Do you mean alerts/ events for a power plant  which is not selected are being displayed in the widget? The filtering is happening on the websocket (using the `id` parameter). If this is filter is working we should only get corresponding events in the widget. Can you give me steps to reproduce?

**Comment by joesan** [comment]
I have this WebSocket Endpoint that sends Alerts and Events for all the PowerPlants:

`ws://localhost:9000/plantsim/powerplant/events
`

This Endpoint can be parameterised like:

`ws://localhost:9000/plantsim/powerplant/events?id=1
`

Which will then give the events and alerts for PowerPlant with id = 1. I filter this in the server and produce the stream!

In the UI, when I toggle between the two radio buttons, I get to see the same set of messages: Here is the step to reproduce this:

1. After opening the [home page](https://plant-simulator-ui.herokuapp.com/ ), click the PowerPlant 1 radio button.
2. Use the following Endpoint to trigger an OutOfService scenario:
    https://cryptic-taiga-18841.herokuapp.com/plantsim/powerplant/1/outofservice
    This would result in an Alert being shown and of course the state change events will be shown
3. Now click the PowerPlant 2 radio button. You will see the same messages even there! This should not be the case. I just verified my WebSocket endpoints and the filter seems to take effect in sending only events and alerts for the given id parameter.

**Comment by sebastianvoss** [comment]
should be fixed in c54588b075848a5e7e01e92fa79033cb5ba594e7
