### ISSUE TITLE
Display SetPoint as an additional graph in the Telemetry HighCharts panel

### ISSUE THREAD

**Issue by joesan** [sebastianvoss/plant-simulator-ui#2]
Currently the Telemetry signals are getting displayed with a legend on the right hand side indicating the activePower. We need an additional series that shows the setPoint. This series should be displayed only when the PowerPlant is being dispatched. Once it finished dispatch, we don't have to show this again! 

I see one possibility of doing this:

1. I can emit the setPoint signal along with the telemetry signals and in the TelemetryWidget.tsx, we can pass in the setPoint, which if undefined, we will not show this second series at all. 

Do you think it works? If you think it might work, let me know so that I can fix my backend to stream the SetPoint signal as well in the telemetry when dispatch happens!

**Comment by sebastianvoss** [comment]
Sounds good. Let me know when you finished the BE.

**Comment by joesan** [comment]
I have this implemented in the backend! You should now get an additional signal in the telemetry with the key setPoint and a double value! You will get this additional signal only for the duration of the dispatch. So if you check for undefined, you can control the hide and show for this data!

Here is a sample data for OnOffType when in dispatch:

{"timestamp":"2018-03-07T22:05:28.894Z","setPoint":100.0,"isOnOff":true,"activePower":100,"powerPlantId":"1","isAvailable":true}

**Comment by sebastianvoss** [comment]
implemented in ca7004a8c5fe881076fe13335c9455d04db18b52
