### ISSUE TITLE
HighCharts display gets reloaded once the PowerPlant transitions state

### ISSUE THREAD

**Issue by joesan** [sebastianvoss/plant-simulator-ui#3]
When I dispatch a PowerPlant from its Active state, the highcharts graph refreshes completely which results in the loss of the old data that was displayed in the chart! The same behavior happens when I ramp down the PowerPlant. Ideally, during state transitions the PowerPlant should stay in the same state as before.

Here it the URL to dispatch a PowerPlant: 

POST: 

https://cryptic-taiga-18841.herokuapp.com/plantsim/powerplant/2/dispatch

PAYLOAD: 

{
  "powerPlantId" : 2,
  "command" : "dispatch",
  "value" : 900.0,
  "powerPlantType" : "RampUpType"
}

Here it the URL to release a PowerPlant: 

POST:

https://cryptic-taiga-18841.herokuapp.com/plantsim/powerplant/2/release

PAYLOAD:

{
  "powerPlantId" : 2
}

**Comment by sebastianvoss** [comment]
fixed in ca7004a8c5fe881076fe13335c9455d04db18b52
